### ISSUE TITLE
mGBA debugging not working

### ISSUE THREAD

**Issue by Aljenci** [JamieDStewart/GBA_VSCode_Basic#5]
Hello!
I am trying your code. All seems to work correct. The rom is generated and I can test it in the emulator and works correctly.
But the debugging don't work.
Using the mGBA version 0.6.2 directly with the vscode the rom don't load, so I changed to another version. I am trying with the version 0.8.3 that is the last, but with others is the same.
With version 0.8.3 the emulator starts with the rom in debug mode correctly, but the vscode show an error:
![image](https://user-images.githubusercontent.com/2663057/89326218-3d453c80-d68a-11ea-8454-6ca37e32b968.png)
All the config seems ok, the debugger address and port (localhost:2345), the devkitPro path and devkitARM path, etc
I tested some more mGBA versions, so I think that is not problem of that version concrete.
Thanks!

**Comment by onecommon-dev** [comment]
I have the same error, but mGBA doesn't even boot up the rom for me. The strange thing is, if I don't close the mGBA window and just run the build again, another window of mGBA opens and loads the rom correctly, but I would still get the "Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information" prompt.
The debug console output will say 

```
Starting: "F:/devkitPro/devkitARM/bin/arm-none-eabi-gdb.exe" --interpreter=mi
"F:/devkitPro/devkitARM/bin/arm-none-eabi-gdb.exe" exited with code -1073741515 (0xC0000135).

```

This happens for mGBA 0.8.3 and mGBA 0.6.2, both 32bit and 64bit.

**Comment by onecommon-dev** [comment]
I managed to resolve my issue. The problem was that devkitPro installation did not add "%DEVKITPRO%\tools\bin" to my path (DEVKITPRO is the path to your devkitPro folder). 

Trying to run arm-none-eabi-gdb.exe directly revealed the problem to me, it was complaining that it couldn't find the mingw dlls that was supposed to come with devkitPro.

**Comment by Aljenci** [comment]
Hello hoangbv15!

Today I have some time to continue testing and definitely is the same. Adding the "%DEVKITPRO%\tools\bin" to the Path solve the problem.

Thank you very much! :+1:

**Comment by Aljenci** [comment]
If it is fine I will make a pull request with this added in the readme.

**Comment by nightblade9** [comment]
Adding the path to devkitpro\tools\bin also solved it for me, a README update PR would be 👌

**Comment by Cryosignal** [comment]
I don't mean to be hijacking this post but I have the same issue. Adding the path did not fix my issue. Same issue as above, but my debugger windows says "Starting: "C:/devkitPro/devkitARM/bin/arm-none-eabi-gdb.exe" --interpreter=mi
"C:/devkitPro/devkitARM/bin/arm-none-eabi-gdb.exe" exited with code -1073741515 (0xC0000135)."

**Comment by JamieDStewart** [comment]
Hi I'll update the project to reflect that the environment variables may need to be set for DEVKITPRO, and Cryosignal I think I have sussed your issue on a separate thread.
