### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate)

### ISSUE THREAD

**Issue by JonJust** [JamieDStewart/GBA_VSCode_Basic#6]
I posted this same issue in the cpptools repo as well, but it is still unresolved so I will post it here as well. Also, to Jamie, if you are reading this, your video series on GBA development is absolute excellent, and really helped me get started in homebrew development. :)

I am using VSCode to develop homebrew for the Game Boy Advance. Everything was working fine until I opened VSCode one day and the debugger stopped working. 

Whenever I go to run and debug my code, this error pops up, "Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate)". Sometimes, the game I am working on will pop up on the emulator before the I get the error message, and be able to play. Other times, the error message pops up and the emulator doesn't even load the game. Regardless, I am unable to use breakpoints or anything along those lines.

Note: I do have ms-vscode-cpptools installed and active in my VSCode, and have reloaded VSCode several times now to no avail.

I used a popular tutorial to configure my JSON to load the code into a GBA emulator.

My Launch.json looks like this:

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "gdb-debug", 
            "postDebugTask": "stop emulation",
            "serverLaunchTimeout": 10000,
            "stopAtEntry": true,
            "program": "${workspaceFolder}/${workspaceFolderBasename}.elf",
            "MIMode": "gdb",
            "externalConsole": true,
            "cwd": "${workspaceFolder}",
            "targetArchitecture": "arm",
            "miDebuggerServerAddress": "localhost:2345",
            "windows": {
                "miDebuggerPath": "C:/devkitPro/devkitARM/bin/arm-none-eabi-gdb.exe",
                "setupCommands": [
                    {
                    "description": "Enable pretty-printing for gdb",
                    "ignoreFailures": true,
                        "text": "file ${workspaceFolder}/${workspaceFolderBasename}.elf -enable-pretty-printing"
                    }]
            },
            "osx":{
                "miDebuggerPath": "/opt/devkitPro/devkitARM/bin/arm-none-eabi-gdb",
                "setupCommands": [
                    {
                    "description": "Enable pretty-printing for gdb",
                    "ignoreFailures": true,
                        "text": "file ${workspaceFolder}/${workspaceFolderBasename}.elf -enable-pretty-printing"
                    }]
            },
        }
    ]
}
```

### Platform and Versions

- **Operating System**: Windows 10
- **C/C++**: v0.29.0
- **VSCode Version**: 1.48.0

### Other Notes/Information
I hope I did a decent job of outlining the problem, I am newer to forum posts like this. If there is any more information needed I would be pleased to update the post.

Edit for people of the future: The templates that I am working with are provided by Jamie D Stewart, with his repository listed [here
](https://github.com/JamieDStewart/GBA_VSCode_Basic). The video series he has documenting the basics of GBA development are can be found [here](https://youtu.be/Rj0lf46iljc).

**Comment by JamieDStewart** [comment]
Glad to hear your enjoying GBA development, and yes I need to get off my backside and get some more tutorial content up. 
I'm going to close this as this seems to be an issue with the cpp extension not activating, your launch.json looks fine compared to the one that I use.
